version: '3.3'

services:
  # mongoDB services
  mongodb:
    container_name: dbcontainer
    image: mongo:latest
    restart: always
    env_file: ./.env
    volumes:
      - mongo_db_data:/data/db
    ports:
      - 27017:27017

  backend:
    build: ./server
    command: npm run dev
    restart: always
    volumes:
      - ./server:/app/backend
    ports:
      - "7000:7000"
    env_file:
      - server/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/diplom
    depends_on:
      - mongodb

volumes:
  mongo_db_data: