const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const eventRouter = require('./eventRouter')
const vacationRouter = require('./vacationRouter')
const dayOffRouter = require('./dayOffRouter')
const locationRouter = require('./locationRouter')
const positionRouter = require('./positionRouter')
const genderRouter = require('./genderRouter')
const statusCandidateRouter = require('./statusCandidateRouter')
const statusDayOffRouterRouter = require('./statusDayOffRouter')
const typeDayOffRouterRouter = require('./typeDayOffRouter')
const roleRouter = require('./roleRouter')
const mainVacationDurationRouter = require('./mainVacationDurationRouter')


router.use('/user', userRouter)
router.use('/event', eventRouter)
router.use('/vacation', vacationRouter)
router.use('/dayoff', dayOffRouter)
router.use('/location', locationRouter)
router.use('/position', positionRouter)
router.use('/gender', genderRouter)
router.use('/dotype', typeDayOffRouterRouter)
router.use('/dostatus', statusDayOffRouterRouter)
router.use('/cstatus', statusCandidateRouter)
router.use('/role', roleRouter)
router.use('/vduration', mainVacationDurationRouter)

module.exports = router